spring:
  application:
    name: junyong-financial

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver

  redis:
    host: localhost
    port: 6379

  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LXJlc2VydmF0aW9uLXByb2plY3Qtand0LXNlY3JldC10b2tlbgo

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"